engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - client/**
  - server/**
  - imports/**
exclude_paths:
- client/stylesheets/blueprint.css
- client/stylesheets/blueprint-datetime.css
- node_modules/**/*
