sudo: required

language: node_js

node_js:
  - "6"
  - "0.10"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules

before_script:
  - meteor npm install

script:
  - meteor build ../output/mongoclient.tar.gz
